name: Update JSON

on:
  schedule:
    - cron: "*/10 * * * *"  
  workflow_dispatch:          

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests
          playwright install chromium

      - name: Run scraper
        env:
          STREAM_URL: ${{ secrets.STREAM_URL }}
          CHANNELS_JSON: ${{ secrets.CHANNELS_JSON }}   # 🔗 এখানে শুধু URL থাকবে (যেমন: https://unosottor.pages.dev/bpk-web/channels.json)
        run: python fetch.py

      - name: Commit and push updated playlist.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add playlist.json
          git commit -m "🔄 Auto-update playlist.json [$(date)]" || echo "No changes"
          git push
