name: Update Playlist

on:
  schedule:
    - cron: '*/10 * * * *'  
  workflow_dispatch:         

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STREAM_URL: ${{ secrets.STREAM_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: Fetch and Update JSON Playlist
        run: python fetch.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add playlist.json
          git commit -m "🔄 Auto-update playlist.json" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
